USE [master]
GO
/****** Object:  Database [MessageSystem]    Script Date: ********* PM ******/
CREATE DATABASE [MessageSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MessageSystem', FILENAME = N'[DataFilePath]\MessageSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MessageSystem_log', FILENAME = N'[DataFilePath]\MessageSystem.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MessageSystem] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MessageSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MessageSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MessageSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MessageSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MessageSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MessageSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [MessageSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MessageSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MessageSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MessageSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MessageSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MessageSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MessageSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MessageSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MessageSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MessageSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MessageSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MessageSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MessageSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MessageSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MessageSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MessageSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MessageSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MessageSystem] SET RECOVERY FULL 
GO
ALTER DATABASE [MessageSystem] SET  MULTI_USER 
GO
ALTER DATABASE [MessageSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MessageSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MessageSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MessageSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MessageSystem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MessageSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MessageSystem', N'ON'
GO
ALTER DATABASE [MessageSystem] SET QUERY_STORE = OFF
GO
USE [MessageSystem]
GO
/****** Object:  Schema [app]    ********** ******/
CREATE SCHEMA [app]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
USE [MessageSystem]
GO

/****** Object: Table [dbo].[Message] Script Date: 2025-03-01 10:48:41 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Message] (
    [PhoneNumber]  BIGINT NOT NULL,
    [MessageCount] INT    NOT NULL,
	CONSTRAINT PK_MESSAGE_PHONE_NUMBER PRIMARY KEY CLUSTERED (PhoneNumber)
);
/****** Object: Table [dbo].[Setting] Script Date: 2025-03-01 10:34:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Setting] (
    [KeyName] NVARCHAR (50) NOT NULL,
    [Value]   NVARCHAR (50) NOT NULL,
	CONSTRAINT PK_SETTINGS_KEYNAME PRIMARY KEY CLUSTERED (KeyName)
);
/******* Seed Data *************************/
INSERT Setting(KeyName,Value) VALUES('MESSAGE_COUNT','0');
INSERT Setting(KeyName,Value) VALUES('MESSAGE_TIME_LIMIT','10000000');
INSERT Setting(KeyName,Value) VALUES('MESSAGES_LIFE_SPAN','3600000000');
/******************************************/